"""Add location to companies

Revision ID: 73f596d379ab
Revises: 80be69d88ad6
Create Date: 2026-08-30 19:36:23.983246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f596d379ab'
down_revision: Union[str, Sequence[str], None] = '80be69d88ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('location', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('jd_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'jd_link')
    op.drop_column('companies', 'location')
    # ### end Alembic commands ###
