"""auto

Revision ID: 80be69d88ad6
Revises: b64b3654fad1
Create Date: 2026-08-30 18:27:10.304718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80be69d88ad6'
down_revision: Union[str, Sequence[str], None] = 'b64b3654fad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('upload_batch_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_students_upload_batch_id'), 'students', ['upload_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_upload_batch_id'), table_name='students')
    op.drop_column('students', 'upload_batch_id')
    # ### end Alembic commands ###
